resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tags: latest-final

resources:
- name: pcf-automation
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: platform-automation

- name: installation
  type: s3
  source:
    access_key_id: {{access_key}}
    bucket: state
    region_name: us-east-1
    secret_access_key: {{secret_key}}
    regexp: ((foundation))/(.*)-installation.zip
    skip_ssl_verification: true
    endpoint: {{s3_endpoint}}

- name: state
  type: s3
  source:
    access_key_id: {{access_key}}
    bucket: state
    region_name: us-east-1
    secret_access_key: {{secret_key}}
    regexp: ((foundation))/(.*)-state.yml
    skip_ssl_verification: true
    endpoint: {{s3_endpoint}}

- name: configuration
  type: git
  source:
    uri: git@github.com:calebwashburn/platform-automation-reference.git
    private_key: {{git_private_key}}

jobs:
- name: install-opsman
  serial: true
  serial_groups: [ install ]
  plan:
  - aggregate:
    - get: configuration
      trigger: true
      params:
        unpack: true
    - get: pcf-automation-image
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*image*"]
    - get: pcf-automation-tasks
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*tasks*"]
    - get: state
  - task: remove-timestamp
    image: pcf-automation-image
    config:
      platform: linux
      inputs:
      - name: state
      outputs:
      - name: timestamp-state
      run:
        path: /bin/bash
        args:
        - -c
        - |
          mv state/*state.yml timestamp-state/state.yml
  - task: credhub-interpolate
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/credhub-interpolate.yml
    params:
      CREDHUB_CLIENT: ((credhub-client))
      CREDHUB_SECRET: ((credhub-secret))
      CREDHUB_SERVER: ((credhub-server))
      CREDHUB_CA_CERT: ((credhub-ca))
      PREFIX: '/((foundation))'
      INTERPOLATION_PATH: "environments/((foundation))/config/secret_templates environments/((foundation))/config/versions"
    input_mapping:
      files: configuration
  - task: download-opsman-image
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/download-product.yml
    input_mapping:
      config: interpolated-files
    params:
      CONFIG_FILE: environments/((foundation))/config/versions/opsman.yml
  - task: create-vm
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/create-vm.yml
    input_mapping:
      image: downloaded-product
      state: timestamp-state
      config: configuration
      vars: configuration
    params:
      STATE_FILE: state/state.yml
      OPSMAN_CONFIG_FILE: environments/((foundation))/config/templates/opsman.yml
      VARS_FILES: config/environments/((foundation))/config/vars/common.yml config/((foundation))/config/vars/opsman.yml
  - task: add-timestamp
    image: pcf-automation-image
    config:
      platform: linux
      inputs:
      - name: generated-state
      outputs:
      - name: timestamp-state
      run:
        path: /bin/bash
        args:
        - -c
        - |
          ts=$(date +"%Y%m%M%S%N")
          mv generated-state/state.yml timestamp-state/${ts}-state.yml
  - put: state
    params:
      file: timestamp-state/*-state.yml
  - task: configure-authentication
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/configure-authentication.yml
    attempts: 20
    input_mapping:
      env: interpolated-files
      config: interpolated-files
    params:
      ENV_FILE: environments/((foundation))/config/templates/env.yml
      AUTH_CONFIG_FILE: environments/((foundation))/config/templates/auth.yml
  - task: configure-director
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/configure-director.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      ENV_FILE: environments/((foundation))/config/templates/env.yml
      DIRECTOR_CONFIG_FILE: environments/((foundation))/config/templates/director.yml
      VARS_FILES: config/environments/((foundation))/config/vars/common.yml config/((foundation))/config/vars/director.yml
  - task: apply-director-changes
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/apply-director-changes.yml
    input_mapping:
      env: interpolated-files
    params:
      ENV_FILE: environments/((foundation))/config/templates/env.yml

- name: export-installation
  serial: true
  serial_groups: [ install ]
  plan:
  - aggregate:
    - get: configuration
      trigger: true
      passed: [ install-opsman ]
      params:
        unpack: true
    - get: pcf-automation-image
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*image*"]
    - get: pcf-automation-tasks
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*tasks*"]
  - task: credhub-interpolate
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/credhub-interpolate.yml
    params:
      CREDHUB_CLIENT: ((credhub-client))
      CREDHUB_SECRET: ((credhub-secret))
      CREDHUB_SERVER: ((credhub-server))
      CREDHUB_CA_CERT: ((credhub-ca))
      PREFIX: '/((foundation))'
      INTERPOLATION_PATH: "environments/((foundation))/config/secret_templates environments/((foundation))/config/versions"
    input_mapping:
      files: configuration
  - task: export-installation
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/export-installation.yml
    input_mapping:
      env: interpolated-files
    params:
      ENV_FILE: environments/((foundation))/config/templates/env.yml
  - task: add-timestamp
    image: pcf-automation-image
    config:
      platform: linux
      inputs:
      - name: installation
      outputs:
      - name: timestamp-installation
      run:
        path: /bin/bash
        args:
        - -c
        - |
          ts=$(date +"%Y%m%M%S%N")
          mv installation/installation.zip timestamp-installation/${ts}-installation.zip
  - put: installation
    params:
      file: timestamp-installation/*-installation.zip

- name: upgrade-opsman
  serial: true
  serial_groups: [ install ]
  plan:
  - aggregate:
    - get: configuration
      trigger: true
      passed: [ export-installation ]
      params:
        unpack: true
    - get: pcf-automation-image
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*image*"]
    - get: pcf-automation-tasks
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*tasks*"]
    - get: installation
      passed: [ export-installation ]
    - get: state
  - task: credhub-interpolate
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/credhub-interpolate.yml
    params:
      CREDHUB_CLIENT: ((credhub-client))
      CREDHUB_SECRET: ((credhub-secret))
      CREDHUB_SERVER: ((credhub-server))
      CREDHUB_CA_CERT: ((credhub-ca))
      PREFIX: '/((foundation))'
      INTERPOLATION_PATH: "environments/((foundation))/config/secret_templates environments/((foundation))/config/versions"
    input_mapping:
      files: configuration
  - task: remove-timestamp
    image: pcf-automation-image
    config:
      platform: linux
      inputs:
      - name: state
      - name: installation
      outputs:
      - name: timestamp-state
      - name: timestamp-installation
      run:
        path: /bin/bash
        args:
        - -c
        - |
          mv state/*state.yml timestamp-state/state.yml
          mv installation/*installation.zip timestamp-installation/installation.zip
  - task: download-opsman-image
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/download-product.yml
    input_mapping:
      config: interpolated-files
    params:
      CONFIG_FILE: environments/((foundation))/config/versions/opsman.yml
  - task: upgrade-opsman
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/upgrade-opsman.yml
    input_mapping:
      image: downloaded-product
      state: timestamp-state
      config: configuration
      env: interpolated-files
      installation: timestamp-installation
      vars: configuration
    params:
      ENV_FILE: environments/((foundation))/config/templates/env.yml
      OPSMAN_CONFIG_FILE: environments/((foundation))/config/templates/opsman.yml
      VARS_FILES: config/environments/((foundation))/config/vars/common.yml config/((foundation))/config/vars/opsman.yml
      STATE_FILE: state.yml
  - task: add-timestamp
    image: pcf-automation-image
    config:
      platform: linux
      inputs:
      - name: generated-state
      outputs:
      - name: timestamp-state
      run:
        path: /bin/bash
        args:
        - -c
        - |
          ts=$(date +"%Y%m%M%S%N")
          mv generated-state/state.yml timestamp-state/${ts}-state.yml
  - put: state
    params:
      file: timestamp-state/*-state.yml

- name: pas
  serial: true
  plan:
  - aggregate:
    - get: configuration
      trigger: true
      passed: [ upgrade-opsman ]
      params:
        unpack: true
    - get: pcf-automation-image
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*image*"]
    - get: pcf-automation-tasks
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*tasks*"]

  - task: credhub-interpolate
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/credhub-interpolate.yml
    params:
      CREDHUB_CLIENT: ((credhub-client))
      CREDHUB_SECRET: ((credhub-secret))
      CREDHUB_SERVER: ((credhub-server))
      CREDHUB_CA_CERT: ((credhub-ca))
      PREFIX: '/((foundation))'
      INTERPOLATION_PATH: "environments/((foundation))/config/secret_templates environments/((foundation))/config/versions"
    input_mapping:
      files: configuration
  - task: download-cf
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/download-product.yml
    input_mapping:
      config: interpolated-files
    params:
      CONFIG_FILE: environments/((foundation))/config/versions/cf.yml

  - task: upload-product
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/upload-product.yml
    input_mapping:
      product: downloaded-product
      env: interpolated-files
    params:
      ENV_FILE: environments/((foundation))/config/templates/env.yml

  - task: stage-product
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/stage-product.yml
    input_mapping:
      product: downloaded-product
      env: interpolated-files
    params:
      ENV_FILE: environments/((foundation))/config/templates/env.yml

  - task: upload-pas-stemcell
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/upload-stemcell.yml
    input_mapping:
      env: interpolated-files
      stemcell: downloaded-stemcell
    params:
      ENV_FILE: environments/((foundation))/config/templates/env.yml

  - task: assign-stemcell
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/upload-stemcell.yml
    input_mapping:
      env: interpolated-files
      config: assign-stemcell-config
    params:
      ENV_FILE: environments/((foundation))/config/templates/env.yml

  - task: configure-pas
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: configuration
      env: interpolated-files
      vars: configuration
      secrets: interpolated-files
    params:
      CONFIG_FILE: environments/((foundation))/config/templates/cf.yml
      VARS_FILES: vars/((foundation))/config/vars/cf.yml
      ENV_FILE: environments/((foundation))/config/templates/env.yml

  - task: apply-product-changes
    image: pcf-automation-image
    config:
      platform: linux
      inputs:
      - name: env
      params:
        ENV_FILE: environments/((foundation))/config/templates/env.yml
      run:
        path: /bin/bash
        args:
        - -c
        - |
          cat /var/version && echo ""
          set -eux
          om --env env/"${ENV_FILE}" apply-changes --product-name cf
    input_mapping:
      env: interpolated-files
    params:
      ENV_FILE: environments/((foundation))/config/templates/env.yml
