enable_silk_policy_enforcement: true
enable_smb_volume_driver: false
garden_disk_cleanup/reserved/reserved_space_for_other_jobs_in_mb: 15360
gorouter_ssl_ciphers: ECDHE-RSA-AES128-GCM-SHA256:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
haproxy_max_buffer_size: 16384
haproxy_ssl_ciphers: DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
isolated_router/disable_insecure_cookies: false
isolated_router/drain_wait: 20
isolated_router/enable_write_access_logs: true
isolated_router/enable_zipkin: true
isolated_router/lb_healthy_threshold: 20
isolated_router/request_timeout_in_seconds: 900
route_services_internal_lookup: false
router_backend_max_conn: 500
router_enable_proxy: false
routing_disable_http: false
skip_cert_verify: false
isolated_diego_cell_instance_type: automatic
isolated_diego_cell_instances: automatic
isolated_ha_proxy_instance_type: automatic
isolated_ha_proxy_instances: automatic
isolated_router_instance_type: automatic
isolated_router_instances: automatic
