cloud_controller/apps_domain: cfapps.haas-415.pez.pivotal.io
cloud_controller/system_domain: run.haas-415.pez.pivotal.io
mysql_monitor/recipient_email: cwashburn@pivotal.io
network_name: deployment
security_acknowledgement: X
singleton_availability_zone: AZ1
ha_proxy/skip_cert_verify: false
router/static_ips:
control/static_ips: 192.168.2.13
az2_name: AZ2
az3_name: AZ3
credhub_key_encryption_passwords_0/name: credhub
networking_poe_ssl_certs_0/name: wildcard
credhub_key_encryption_passwords_0/primary: true
stack_migration_acknowledgement: X
tcp_router_instances: 0
router_instances: 2
compute_instances: 5
router_additional_vm_extensions: ["router-lb"]
