vsphere_resource_pool: /Datacenter/host/Cluster/Resources/dev-az1
opsman_vm_name: dev-opsman
opsman_private_ip: 192.168.1.10
opsman_netmask: 255.255.255.0
vsphere_datastore: LUN01
vsphere_datacenter: Datacenter
infrastructure_network: PAS-Infrastructure
infrastructure_gateway: 192.168.1.1
dns: 10.192.2.10,10.192.2.11
ntp: time.svc.pivotal.io
vsphere_vms_folder: dev-vms
