az2_name: AZ2
az3_name: AZ3
healthwatch-forwarder/foundation_name: haas-415
healthwatch-forwarder/health_check_az: AZ1
network_name: deployment
opsman/enable/url: opsman.haas-415.pez.pivotal.io
service_network_name: deployment
singleton_availability_zone: AZ1
