credhub_key_encryption_passwords_0/key: ((credhub_encryption_key))
networking_poe_ssl_certs_0/certificate: ((wilcard.certificate))
networking_poe_ssl_certs_0/privatekey: ((wilcard.privatekey))
uaa/service_provider_key_credentials/certificate: ((wilcard.certificate))
uaa/service_provider_key_credentials/privatekey: ((wilcard.privatekey))
