credhub_key_encryption_passwords_0/key: ((credhub_encryption_key))
networking_poe_ssl_certs_0/certificate: ((wildcard.certificate))
networking_poe_ssl_certs_0/privatekey: ((wildcard.private_key))
uaa/service_provider_key_credentials/certificate: ((wildcard.certificate))
uaa/service_provider_key_credentials/privatekey: ((wildcard.private_key))
