nsx_admin_password: ((nsx_admin_password))
nsx_admin_user: ((nsx_admin_user))
nsx_ca_cert: ((nsx_ca_cert))
nsx_hostname: ((nsx_hostname))
vcenter_hostname: ((vcenter_hostname))
vcenter_userid: ((vcenter_userid))
vcenter_password: ((vcenter_password))
bosh_trusted_certs: ((wildcard.certificate))
